run:
  timeout: 5m

issues:
  exclude-dirs:
    - .gomodcache

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - revive
    - ineffassign
    - unused

linters-settings:
  gofmt:
    simplify: false